# Generated by Django 4.0.1 on 2022-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='files/thumnail')),
                ('resource', models.FileField(upload_to='files/resource')),
                ('active', models.BooleanField(default=False)),
                ('length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
