# Generated by Django 4.0.1 on 2022-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='files/resource'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=70),
        ),
    ]
