# Generated by Django 4.0.1 on 2022-02-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
