# Generated by Django 4.0.2 on 2022-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BG', 'Beginner'), ('INT', 'Intermediate'), ('AD', 'Advanced')], default='BG', max_length=3),
        ),
    ]
