# Generated by Django 4.0.2 on 2022-02-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
