# Generated by Django 4.0.2 on 2022-03-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
