# Generated by Django 4.0.2 on 2022-03-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
